/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.lilybukkit.dandelion;

import net.buj.rml.Environment;
import net.buj.rml.RosepadMod;

public class Dandelion extends RosepadMod {
    @Override
    public void pre(Environment environment) {

    }

    @Override
    public void init(Environment environment) {

    }
}
