/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.lilybukkit.dandelion;

import org.junit.Test;
import static org.junit.Assert.*;

public class DandelionTest {
    @Test public void someLibraryMethodReturnsTrue() {
        Dandelion classUnderTest = new Dandelion();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
